name: Build and debug PJSIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            env.BUILDKIT_PROGRESS=plain

      - name: Build with full logs
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: false
          load: true
          tags: test:latest
          builder: default
          outputs: type=local,dest=./out
